### ISSUE TITLE
Top Text

### ISSUE THREAD

**Issue by RiversideRocks** [youngchief-btw/mrocha.tk#1]
The top text is a bit hard to read on the background.

**Comment by youngchief-btw** [comment]
Yes I agree, I have been having trouble finding a good color for the text.

**Comment by RiversideRocks** [comment]
You could always put a div around the text and change the background color of the div.

**Comment by youngchief-btw** [comment]
Could you implement it in a pull request? @RiversideRocks

**Comment by RiversideRocks** [comment]
Sure! I will get that done a bit later.

**Comment by youngchief-btw** [comment]
👍

**Comment by youngchief-btw** [comment]
Working on it!

**Comment by youngchief-btw** [comment]
Fixed! I decided to use pink as the color.
